services:
  - type: web
    name: studymate-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: web
    name: studymate-frontend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
