type: web
  name: studymate-backend
  env: python
  buildCommand: pip install -r backend/requirements.txt
  startCommand: gunicorn app:app
  workingDir: backend
  envVars:
    - key: PYTHON_VERSION
      value: 3.10
